### ISSUE TITLE
Inet doesn't support host addresses

### ISSUE THREAD

**Issue by ccakes** [jackc/pgtype#111]
I feel like this should definitely be supported and I'm doing something wrong, but `pgtype.Inet` seems to be wiping out the host bits of any addresses I pass in.

```go
var v4addr pgtype.Inet
if err := v4addr.Set("192.0.2.10/24"); err != nil {
  fmt.Errorf("Error: %v", err)
}

fmt.Printf("Parsed addr: %v", v4addr) // will print 192.0.2.0/24
```

The `Cidr` type should behave this way, but `Inet` should allow host addresses with a mask length - [Postgres docs](https://www.postgresql.org/docs/current/datatype-net-types.html#DATATYPE-INET-VS-CIDR)

What am I doing wrong?

**Comment by jackc** [comment]
Hmm. It looks like https://golang.org/pkg/net/#ParseCIDR automatically zeros the masked portion of the `net.IPNet` it returns.

I've made a change that should resolve it, though it probably bends what Go expects an `net.IPNet` to be.

**Comment by ccakes** [comment]
This is still an issue unfortunately, `mustParseCIDR` in [pgtype_test.go](https://github.com/jackc/pgtype/blob/2ca304d4617a72491b1844eb92e9ecd86f7b84e9/pgtype_test.go#L30) has the same behaviour which masks the failing test case.

Making that change locally seems to throw a bit of a spanner in the works for the Inet type though

```
$ go test -v ./... -run TestInetTranscode | grep 192.168.1.50
    testutil.go:159: Param TextFormat Result TextFormat 4: expected {192.168.1.50/24 2}, got {192.168.1.0/24 2}
    testutil.go:159: Param TextFormat Result BinaryFormat 4: expected {192.168.1.50/24 2}, got {192.168.1.50/24 2}
    testutil.go:159: Param BinaryFormat Result TextFormat 4: expected {192.168.1.50/24 2}, got {::/24 2}
    testutil.go:159: Param BinaryFormat Result BinaryFormat 4: expected {192.168.1.50/24 2}, got {192.168.1.50/0 2}
    testutil.go:190: github.com/lib/pq 4: expected {192.168.1.50/24 2}, got {192.168.1.0/24 2}
    testutil.go:190: github.com/jackc/pgx/stdlib 4: expected {192.168.1.50/24 2}, got {::/24 2}
    testutil.go:155: Param TextFormat Result TextFormat 4: ERROR: invalid cidr value: "192.168.1.50/24" (SQLSTATE 22P02)
    testutil.go:159: Param TextFormat Result TextFormat 4: expected {192.168.1.50/24 2}, got {<nil> 0}
    testutil.go:155: Param TextFormat Result BinaryFormat 4: ERROR: invalid cidr value: "192.168.1.50/24" (SQLSTATE 22P02)
    testutil.go:159: Param TextFormat Result BinaryFormat 4: expected {192.168.1.50/24 2}, got {<nil> 0}
    testutil.go:159: Param BinaryFormat Result TextFormat 4: expected {192.168.1.50/24 2}, got {<nil> 0}
    testutil.go:159: Param BinaryFormat Result BinaryFormat 4: expected {192.168.1.50/24 2}, got {<nil> 0}
    testutil.go:186: github.com/lib/pq 4: pq: invalid cidr value: "192.168.1.50/24"
    testutil.go:190: github.com/lib/pq 4: expected {192.168.1.50/24 2}, got {<nil> 0}
    testutil.go:190: github.com/jackc/pgx/stdlib 4: expected {192.168.1.50/24 2}, got {<nil> 0}
```

> I've made a change that should resolve it, though it probably bends what Go expects an net.IPNet to be.

I'm working on a PR to try fix it up, though if you'd rather keep the behaviour that these types currently have let me know and I can look at a different type for deserialising `inet` fields
